
# SEO settings
title: Neuron Sketch
description: "A blog about computational neuroscience"
keywords: "computational neuroscience, NEST, network dynamics, recurrent network"
#url: http://hanlu.io
#baseurl: "/blog"
# baseurl: null

<<<<<<< HEAD
# navbar pages
navbar:
  - slug : /about
    title: About
  - slug : /archive
    title: Archive



# Author settings
author:
  name     : Han Lu # Also the name shown on the front page
  job      : PhD Student # Also the profession shown on the front page
  bio      : "[Here is a short intro]" # Also shown on the front page
  thumb    : /assets/images/author.jpg # change it as you wish
  email    : luhan040710@foxmail.com 
  url      : http://hanlu.io
  github   : http://github.com/ErbB4
  #twitter  : http://twitter.com/nandomoreirame # change this
  #facebook : http://facebook.com/fernando.dev
  #linkedin : http://linkedin.com/in/nandomoreirame
  resumelink: http://hanlu.io

# social settings
og_locale: "pt_BR"
twitter_card: "summary_large_image"
twitter_site: "@nandomoreirame"

google_analytics: 
repo: https://github.com/ErbB4/blog
disqus_shortname: "neuron-sketch"
=======
google_analytics: UA-52446115-1
repo: http://github.com/nandomoreirame/simplest
disqus_shortname: "nandothemes"
>>>>>>> 867ffde56522ca44c8ab33974ec96ac9efe88dff

# Build settings
permalink   : /:title/
markdown    : kramdown
highlighter : rouge

# paginate: 4
# paginate_path: "/page/:num/"
comments: true

# source: source
# destination: _site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded



gems:
  # - bourbon
  # - jekyll-paginate


exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
